### ISSUE TITLE
Error: Unexpected "<?xml" on line 1.

### ISSUE THREAD

**Issue by colwilson** [rdfjs/N3.js#147]
version 1.0.0-beta.2
node v8.11.3

```
var fs = require('fs');
const N3 = require('n3');

const parser = N3.Parser()

const fn = './catalog1.rdf'
const rdfStream = fs.createReadStream(fn)

parser.parse(rdfStream, console.log);
```
./catalog1.rdf
```
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE rdf:RDF [
  <!ENTITY pg  "Project Gutenberg">
  <!ENTITY lic "http://www.gutenberg.org/license">
  <!ENTITY f   "http://www.gutenberg.org/">
]>

<pgterms:etext rdf:ID="etext14600">
  <dc:publisher>&pg;</dc:publisher>
  <dc:title rdf:parseType="Literal">Theory of Silk Weaving
A Treatise on the Construction and Application of Weaves, and the Decomposition and Calculation of Broad and Narrow, Plain, Novelty and Jacquard Silk Fabrics</dc:title>
  <dc:creator rdf:parseType="Literal">Wolfensberger, Arnold</dc:creator>
  <pgterms:friendlytitle rdf:parseType="Literal">Theory of Silk Weaving by Arnold Wolfensberger</pgterms:friendlytitle>
  <dc:language><dcterms:ISO639-2><rdf:value>en</rdf:value></dcterms:ISO639-2></dc:language>
  <dc:subject>
    <rdf:Bag>
      <rdf:li><dcterms:LCSH><rdf:value>Weaving</rdf:value></dcterms:LCSH></rdf:li>
      <rdf:li><dcterms:LCSH><rdf:value>Silk industry</rdf:value></dcterms:LCSH></rdf:li>
    </rdf:Bag>
  </dc:subject>
  <dc:subject><dcterms:LCC><rdf:value>TS</rdf:value></dcterms:LCC></dc:subject>
  <dc:created><dcterms:W3CDTF><rdf:value>2005-01-05</rdf:value></dcterms:W3CDTF></dc:created>
  <pgterms:downloads><xsd:nonNegativeInteger><rdf:value>146</rdf:value></xsd:nonNegativeInteger></pgterms:downloads>
  <dc:rights rdf:resource="&lic;" />
</pgterms:etext>

<pgterms:etext rdf:ID="etext38658">
  <dc:publisher>&pg;</dc:publisher>
  <dc:title rdf:parseType="Literal">Self-Instructor in the Art of Hair Work, Dressing Hair, Making Curls, Switches, Braids, and Hair Jewelry of Every Description.</dc:title>
  <dc:creator rdf:parseType="Literal">Campbell, Mark, 19th cent.</dc:creator>
  <pgterms:friendlytitle rdf:parseType="Literal">Self-Instructor in the Art of Hair Work, Dressing </pgterms:friendlytitle>
  <dc:language><dcterms:ISO639-2><rdf:value>en</rdf:value></dcterms:ISO639-2></dc:language>
  <dc:subject>
    <rdf:Bag>
      <rdf:li><dcterms:LCSH><rdf:value>Hairdressing</rdf:value></dcterms:LCSH></rdf:li>
      <rdf:li><dcterms:LCSH><rdf:value>Jewelry -- Catalogs</rdf:value></dcterms:LCSH></rdf:li>
      <rdf:li><dcterms:LCSH><rdf:value>Hairwork</rdf:value></dcterms:LCSH></rdf:li>
    </rdf:Bag>
  </dc:subject>
  <dc:subject><dcterms:LCC><rdf:value>TT</rdf:value></dcterms:LCC></dc:subject>
  <dc:created><dcterms:W3CDTF><rdf:value>2012-01-24</rdf:value></dcterms:W3CDTF></dc:created>
  <pgterms:downloads><xsd:nonNegativeInteger><rdf:value>134</rdf:value></xsd:nonNegativeInteger></pgterms:downloads>
  <dc:rights rdf:resource="&lic;" />
</pgterms:etext>


</rdf:RDF>

```

results in:

```
{ Error: Unexpected "<?xml" on line 1.
    at N3Lexer._syntaxError (/home/col/dev/play-clear-husky/node_modules/n3/lib/N3Lexer.js:391:15)
    at reportSyntaxError (/home/col/dev/play-clear-husky/node_modules/n3/lib/N3Lexer.js:358:54)
    at N3Lexer._tokenizeToEnd (/home/col/dev/play-clear-husky/node_modules/n3/lib/N3Lexer.js:343:18)
    at ReadStream.<anonymous> (/home/col/dev/play-clear-husky/node_modules/n3/lib/N3Lexer.js:432:16)
    at emitOne (events.js:116:13)
    at ReadStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at ReadStream.Readable.push (_stream_readable.js:208:10)
    at fs.read (fs.js:2058:12)
  context: { token: undefined, line: 1, previousToken: undefined } }
```
this looks like valid rdf to me?

**Comment by RubenVerborgh** [comment]
Yes, but it's RDF/XML, which this library purposely does not support. Only Turtle and derived syntaxes.

**Comment by rubensworks** [comment]
@colwilson You can use this parser for that: https://github.com/rdfjs/rdfxml-streaming-parser.js
It also parses streams and outputs the same format as N3.js (RDFJS).
