### ISSUE TITLE
Passing NamedNode to prefix function throws error

### ISSUE THREAD

**Issue by LaurensRietveld** [rdfjs/N3.js#247]
The following lines throws an error:

```
var N3 = require('n3');
N3.Util.prefix(N3.DataFactory.namedNode('a:a'))
```
The thrown error is:
```
Error: Unknown prefix: 
    at processPrefix (/home/lrd900/triply/N3.js/lib/N3Util.js:78:13)
    at prefixes (/home/lrd900/triply/N3.js/lib/N3Util.js:62:41)
    at Object.prefix (/home/lrd900/triply/N3.js/lib/N3Util.js:52:10)
    at Object.<anonymous> (/home/lrd900/triply/N3.js/test.js:3:9)
```

I'm a bit confused over whether this is a bug or not. The documentation does not specify whether this is supported or not. The typescript interface does explicitly allow passing NamedNodes.

(my 2c: I'd like to support passing NamedNodes here)

**Comment by RubenVerborgh** [comment]
Let's indeed update to support NamedNode.
